file(READ "${INPUT_FILE}" content)
string(REPLACE "\n" ";" lines "${content}")

file(WRITE "${OUTPUT_FILE}" "#include <gtest/gtest.h>\n")
file(APPEND "${OUTPUT_FILE}" "#include \"SquareEquationSolver.h\"\n")

list(POP_FRONT lines header) # delete header for csv-file

set(index 0)
foreach(line IN LISTS lines)

if(line STREQUAL "") # skip empty rows
continue()
endif()


string(REPLACE "," ";" values "${line}")
list(GET values 0 a)
list(GET values 1 b)
list(GET values 2 c)
list(GET values 3 result)

string(STRIP "${a}" a)
string(STRIP "${b}" b)
string(STRIP "${c}" c)
string(STRIP "${result}" result)

if(result STREQUAL "error")
    set(test_body "EXPECT_THROW(solver.solve(${a}, ${b}, ${c}), std::invalid_argument);")
else()
    set(test_body "auto roots = solver.solve(${a}, ${b}, ${c});\n    EXPECT_EQ(roots.size(), ${result});")
endif()

file(APPEND "${OUTPUT_FILE}" "
TEST(AutoGeneratedTest, Case${index}) {
SquareEquationSolver solver;
${test_body}
}\n")

math(EXPR index "${index} + 1")
endforeach()